apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-frontend-conf
data:
  nginx.conf: |
    server {
        listen       80;
        server_name  frontend_;
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        location /login {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
        }

        location /logout {
              root   /usr/share/nginx/html;
              index  index.html index.htm;
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: peterlight/chat_app_react:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: frontend-conf-volume
              mountPath: /etc/nginx/conf.d/
              readOnly: true
      volumes:
        - name: frontend-conf-volume
          configMap:
            name: nginx-frontend-conf
            items:
              - key: nginx.conf
                path: default.conf
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-internal-service
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: frontend

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-external-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
  selector:
    app: frontend